-- Bảng phẳng từ fb.events_raw. FILE NÀY ĐƯỢC SINH TỪ BASE_COLUMNS trong
-- src/fb_pipeline/clickhouse/flat.py — sửa cột cố định thì sửa constant rồi generate lại
-- (unit test tests/test_flat.py đối chiếu hai file).
--
-- Đây chỉ là phần cột CỐ ĐỊNH. Cột động (event_params/user_properties flatten ra,
-- kiểu `<key>_<str|int|float|double>`) được thêm lúc runtime bằng
-- ALTER TABLE ADD COLUMN, điều khiển bởi fb.flat_schema_registry — key mới xuất
-- hiện trong dữ liệu là bảng tự có cột mới.
--
-- PARTITION BY _dt giống events_raw: reprocess một ngày = DROP PARTITION + insert lại
-- từ raw, không đụng BigQuery.
CREATE TABLE IF NOT EXISTS fb.events_flat
(
    `event_date` Date,
    `event_timestamp` Int64,
    `event_ts` DateTime64(6),
    `event_name` String CODEC(ZSTD(1)),
    `event_previous_timestamp` Nullable(Int64),
    `event_value_in_usd` Nullable(Float64),
    `event_bundle_sequence_id` Nullable(Int64),
    `event_server_timestamp_offset` Nullable(Int64),
    `user_id` Nullable(String) CODEC(ZSTD(1)),
    `user_pseudo_id` Nullable(String) CODEC(ZSTD(1)),
    `user_first_touch_timestamp` Nullable(Int64),
    `stream_id` Nullable(String) CODEC(ZSTD(1)),
    `platform` String CODEC(ZSTD(1)),
    `is_active_user` Nullable(Bool),
    `batch_event_index` Nullable(Int64),
    `batch_page_id` Nullable(Int64),
    `batch_ordering_id` Nullable(Int64),
    `privacy_ads_storage` Nullable(String) CODEC(ZSTD(1)),
    `privacy_analytics_storage` Nullable(String) CODEC(ZSTD(1)),
    `privacy_uses_transient_token` Nullable(String) CODEC(ZSTD(1)),
    `event_dimensions_hostname` Nullable(String) CODEC(ZSTD(1)),
    `user_ltv_revenue` Nullable(Float64),
    `user_ltv_currency` Nullable(String) CODEC(ZSTD(1)),
    `device_category` Nullable(String) CODEC(ZSTD(1)),
    `device_mobile_brand_name` Nullable(String) CODEC(ZSTD(1)),
    `device_mobile_model_name` Nullable(String) CODEC(ZSTD(1)),
    `device_mobile_marketing_name` Nullable(String) CODEC(ZSTD(1)),
    `device_mobile_os_hardware_model` Nullable(String) CODEC(ZSTD(1)),
    `device_operating_system` Nullable(String) CODEC(ZSTD(1)),
    `device_operating_system_version` Nullable(String) CODEC(ZSTD(1)),
    `device_vendor_id` Nullable(String) CODEC(ZSTD(1)),
    `device_advertising_id` Nullable(String) CODEC(ZSTD(1)),
    `device_language` Nullable(String) CODEC(ZSTD(1)),
    `device_is_limited_ad_tracking` Nullable(String) CODEC(ZSTD(1)),
    `device_time_zone_offset_seconds` Nullable(Int64),
    `device_browser` Nullable(String) CODEC(ZSTD(1)),
    `device_browser_version` Nullable(String) CODEC(ZSTD(1)),
    `device_web_browser` Nullable(String) CODEC(ZSTD(1)),
    `device_web_browser_version` Nullable(String) CODEC(ZSTD(1)),
    `device_web_hostname` Nullable(String) CODEC(ZSTD(1)),
    `geo_city` Nullable(String) CODEC(ZSTD(1)),
    `geo_continent` Nullable(String) CODEC(ZSTD(1)),
    `geo_country` Nullable(String) CODEC(ZSTD(1)),
    `geo_region` Nullable(String) CODEC(ZSTD(1)),
    `geo_sub_continent` Nullable(String) CODEC(ZSTD(1)),
    `geo_metro` Nullable(String) CODEC(ZSTD(1)),
    `app_info_id` Nullable(String) CODEC(ZSTD(1)),
    `app_info_version` Nullable(String) CODEC(ZSTD(1)),
    `app_info_install_store` Nullable(String) CODEC(ZSTD(1)),
    `app_info_firebase_app_id` Nullable(String) CODEC(ZSTD(1)),
    `app_info_install_source` Nullable(String) CODEC(ZSTD(1)),
    `traffic_source_name` Nullable(String) CODEC(ZSTD(1)),
    `traffic_source_medium` Nullable(String) CODEC(ZSTD(1)),
    `traffic_source_source` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_campaign_id` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_campaign_name` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_source` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_medium` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_term` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_content` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_source_platform` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_creative_format` Nullable(String) CODEC(ZSTD(1)),
    `cts_manual_marketing_tactic` Nullable(String) CODEC(ZSTD(1)),
    `cts_gclid` Nullable(String) CODEC(ZSTD(1)),
    `cts_dclid` Nullable(String) CODEC(ZSTD(1)),
    `cts_srsltid` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_campaign_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_campaign_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_source` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_medium` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_term` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_content` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_source_platform` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_creative_format` Nullable(String) CODEC(ZSTD(1)),
    `stlc_manual_marketing_tactic` Nullable(String) CODEC(ZSTD(1)),
    `stlc_gads_customer_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_gads_account_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_gads_campaign_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_gads_campaign_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_gads_ad_group_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_gads_ad_group_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cross_campaign_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cross_campaign_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cross_source` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cross_medium` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cross_source_platform` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cross_default_channel_group` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cross_primary_channel_group` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_campaign_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_campaign_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_source` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_medium` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_ad_group_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_ad_group_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_creative_format` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_engine_account_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_engine_account_type` Nullable(String) CODEC(ZSTD(1)),
    `stlc_sa360_manager_account_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_campaign_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_campaign_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_source` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_medium` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_account_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_account_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_advertiser_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_advertiser_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_creative_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_creative_format` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_creative_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_creative_type` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_creative_type_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_creative_version` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_placement_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_placement_cost_structure` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_placement_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_rendering_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_site_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_cm360_site_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_campaign_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_campaign_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_source` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_medium` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_advertiser_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_advertiser_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_creative_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_creative_format` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_creative_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_exchange_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_exchange_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_insertion_order_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_insertion_order_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_line_item_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_line_item_name` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_partner_id` Nullable(String) CODEC(ZSTD(1)),
    `stlc_dv360_partner_name` Nullable(String) CODEC(ZSTD(1)),
    `publisher_ad_revenue_in_usd` Nullable(Float64),
    `publisher_ad_format` Nullable(String) CODEC(ZSTD(1)),
    `publisher_ad_source_name` Nullable(String) CODEC(ZSTD(1)),
    `publisher_ad_unit_id` Nullable(String) CODEC(ZSTD(1)),

    -- Metadata
    _dt Date,
    _ingested_at DateTime DEFAULT now(),
    _run_id String CODEC(ZSTD(1))
)
ENGINE = MergeTree
PARTITION BY _dt
ORDER BY (_dt, event_name, user_pseudo_id, event_timestamp)
SETTINGS index_granularity = 8192, allow_nullable_key = 1;
